[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; 1. Serial Monitor Configuration
build_type = debug   
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, default

; ใช้ LittleFS เป็น filesystem
board_build.filesystem = littlefs

; 2. Library Dependencies
lib_deps =
    claws/BH1750 @ ^1.3.0
    adafruit/RTClib @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit SHT4x Library @ ^1.0.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

; 3. Build Flags
build_flags = 
    -D CORE_DEBUG_LEVEL=3        
    -D VERSION=\"1.0.0-SMARTFARM\"  

; 4. Upload Settings
upload_speed = 921600
